apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: app-config
      containers:
        - name: redis
          image: redis:latest
          env:
            - name: CONFIGMAP_PARAM
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: configKey
          volumeMounts:
            - name: config-volume
              mountPath: /config
